version: "3.8"

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    command:
      - "--path.rootfs=/host"
    volumes:
      - "/:/host:ro,rslave"

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"

    environment:
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: "smtp.gmail.com:587"
      GF_SMTP_USER: "pathiyaparalu.ss@gmail.com"
      GF_SMTP_PASSWORD: "meyk lcrb eimt ehbz"
      GF_SMTP_FROM_ADDRESS: "pathiyaparalu.ss@gmail.com"
      GF_SMTP_FROM_NAME: "Grafana Alerts"

    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
